### PR TITLE
chore: add disputes, events, files Stripe objects

### PR DESCRIPTION
**Pull request by burmecia**
## What kind of change does this PR introduce?

This PR is to add more core objects to Stripe fdw.

- Disputes
- Events
- Files
- File Links
- Mandates
- Setup Intents
- Payouts
- Refunds
- Setup Attempts
- Tokens

## What is the current behavior?

N/A

## What is the new behavior?

N/A

## Additional context

N/A

### CODE REVIEW

**Review by olirice — CHANGES_REQUESTED** [review]
looks great, could you please add these to the docs too?

what do you think about dropping the `<wrapper>/README.md` docs in favor of the `/docs` moving forward so we don't have two sources of truth?

**Comment by elvise** [comment]
@burmecia great PR! 
Can you check @olirice ‘s comment?

**Comment by burmecia** [comment]
sure, I've updated the docs and will move all README docs to `docs/` folder once this PR is merged.

**Comment by elvise** [comment]
> sure, I've updated the docs and will move all README docs to `docs/` folder once this PR is merged.

Great! 🙂

**Comment by olirice** [comment]
@burmecia  It didn't occur to me that #24 was holding your ability to move the docs/ over. That has now merged, sorry for the delay!

**Comment by burmecia** [comment]
thanks @olirice , I've removed docs from README and could you review this PR?

**Review by olirice — APPROVED** [review]

**Pull request merged**
